id: A67617C8B
title: CII_ยง2I
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:46:24.239579
  last_modified_at: 2022-03-01 21:46:24.239582
