id: A67617C8B
title: CI_ยง1D
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:46:24.245151
  last_modified_at: 2022-03-01 21:46:24.245154
