id: A67617C8B
title: CI_ยง1X
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:46:24.268683
  last_modified_at: 2022-03-01 21:46:24.268686
