id: A67617C8B
title: CIII_ยง3E
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:46:24.215447
  last_modified_at: 2022-03-01 21:46:24.215450
