id: A67617C8B
title: CIII_ยง3H
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:46:24.221607
  last_modified_at: 2022-03-01 21:46:24.221611
