id: A67617C8B
title: CI_ยง1V
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:46:24.266797
  last_modified_at: 2022-03-01 21:46:24.266800
