id: A67617C8B
title: CII_ยง2B
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:46:24.232187
  last_modified_at: 2022-03-01 21:46:24.232207
