id: A67617C8B
title: CI_ยง1K
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:46:24.254834
  last_modified_at: 2022-03-01 21:46:24.254837
